### ISSUE TITLE
Link in readme to OSC 1.0 -> Page not found

### ISSUE THREAD

**Issue by TobiasSekan** [klingtnet/rosc#18]
Hello,

The link to `OSC 1.0 protocol ` in the `readme.md` looks like outdated

![2021-05-21 10_40_14-Page not found _ CNMAT — Mozilla Firefox](https://user-images.githubusercontent.com/17874713/119108980-0ecdfd80-ba21-11eb-94be-ea4dd497ed1c.png)

**Comment by klingtnet** [comment]
Thank you for the report!  I thought this was fixed with #16 but it broke again.  Will fix it right away.

**Comment by klingtnet** [comment]
The link now points to https://github.com/CNMAT/OpenSoundControl.org/blob/master/spec-1_0.md .
