### ISSUE TITLE
Possible small bug?

### ISSUE THREAD

**Issue by aleixjf** [klingtnet/rosc#39]
Hello,

I've found an error while compiling after having upgraded to rosc 0.9.1 from version 0.8.

```console
Compiling rosc v0.9.1
error[E0449]: unnecessary visibility qualifier
   --> /Users/<my-username>/.cargo/registry/src/github.com-1ecc6299db9ec823/rosc-0.9.1/src/types.rs:106:5
    |
106 |     pub fn from(time: (u32, u32)) -> OscTime {
    |     ^^^ `pub` not permitted here because it's implied
```

I've temporarily solved it by following the suggested solution and removing the pub modifier.

**Comment by klingtnet** [comment]
There's also no `pub` modifier assigned to this function in rosc 0.9.1:

```sh
$ git describe --tags
v0.9.1
$ rg -A3 --fixed-strings 'fn from(time: (u32, u32)) -> Self' src/types.rs
198:    fn from(time: (u32, u32)) -> Self {
199-        OscType::Time(time.into())
200-    }
201-}
```

🤔

**Comment by klingtnet** [comment]
I think this can be closed since there's no `pub` modifier here.  The issue might have been a false positive.  Please reopen if this error occurs again.
