### ISSUE TITLE
bundle time tag is OscType, feels like it should be a (u32, u32)

### ISSUE THREAD

**Issue by x37v** [klingtnet/rosc#9]
according to : http://opensoundcontrol.org/spec-1_0
A bundle always has a time tag, which is always 8 bytes.

rosc's [OscBundle.timetag](https://docs.rs/rosc/0.3.0/rosc/struct.OscBundle.html#structfield.timetag) is an `OscType` which means a user must use a match to extract the data. 
It seems like it should just be a `(u32, u32)`.

**Comment by klingtnet** [comment]
Thank you for reporting this!
I opened a new pull request where I added a new type for OSC time tags called `OscTime`.
My Rust skills are pretty rusty (pun intended), so I am not sure if this is really idiomatic.
If you don't mind you can do a review of https://github.com/klingtnet/rosc/pull/10 .
